name: quran_learning_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  country_picker: ^2.0.28
  timezone: ^0.11.1
  bottom_navy_bar: ^6.1.0
  flutter_zoom_drawer: ^3.2.0
  supabase_flutter: ^2.15.4
  flutter_dotenv: ^6.0.1
  intl: ^0.20.3
  image_picker: ^1.2.3
  http: ^1.6.0
  audioplayers: ^6.8.1
  font_awesome_flutter: ^11.0.0
  permission_handler: ^12.0.3
  file_picker: ^10.3.10
  shared_preferences: ^2.5.5
  video_player: ^2.13.0
  chewie: ^1.13.1
  path_provider: ^2.1.6
  just_audio: ^0.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/qaida/
    - .env