// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1w5Wavv2aX_l32zmspZGR4fB-ZJAB3Ow',
    appId: '1:563119912380:web:5ea61fb802c119472fe7b9',
    messagingSenderId: '563119912380',
    projectId: 'faaz-al-quran',
    authDomain: 'faaz-al-quran.firebaseapp.com',
    storageBucket: 'faaz-al-quran.firebasestorage.app',
    measurementId: 'G-LC3WY2R3DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACBD9Unq4wBH0G9xlXYfJMhWSbMaXSd3s',
    appId: '1:563119912380:android:958b7bee7c6b37302fe7b9',
    messagingSenderId: '563119912380',
    projectId: 'faaz-al-quran',
    storageBucket: 'faaz-al-quran.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK4WcPVOf17J2HPH7uElmLqSbUL7gAUEQ',
    appId: '1:563119912380:ios:ee7aaff9b072079e2fe7b9',
    messagingSenderId: '563119912380',
    projectId: 'faaz-al-quran',
    storageBucket: 'faaz-al-quran.firebasestorage.app',
    iosBundleId: 'com.example.quranLearningApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK4WcPVOf17J2HPH7uElmLqSbUL7gAUEQ',
    appId: '1:563119912380:ios:ee7aaff9b072079e2fe7b9',
    messagingSenderId: '563119912380',
    projectId: 'faaz-al-quran',
    storageBucket: 'faaz-al-quran.firebasestorage.app',
    iosBundleId: 'com.example.quranLearningApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1w5Wavv2aX_l32zmspZGR4fB-ZJAB3Ow',
    appId: '1:563119912380:web:e5774143bbfcc9172fe7b9',
    messagingSenderId: '563119912380',
    projectId: 'faaz-al-quran',
    authDomain: 'faaz-al-quran.firebaseapp.com',
    storageBucket: 'faaz-al-quran.firebasestorage.app',
    measurementId: 'G-3LZ78LJH6Z',
  );
}
